<a href="https://colab.research.google.com/github/sireeshareddy065-siree/Task16/blob/main/day16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
text = 'Hello! This is a SAMPLE Email to check Sireesha and Akshaya. Are looking at Screen.'
text_lower = text.lower()
print(text_lower)

hello! this is a sample email to check sireesha and akshaya. are looking at screen.


In [ ]:
import re
text = 'Hello! This is a SAMPLE Email to check Sireesha and Akshaya. Are looking at Screen.'
text_clean = re.sub(r'[^a-z]', ' ', text)
print(text_clean)

 ello   his is a         mail to check  ireesha and  kshaya   re looking at  creen 


In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords', quiet=True)
stop_word = set(stopwords.words('english'))
text = "Iam going to college today"
token = []
for word in text.split():
    if word not in stop_word:
        token.append(word)
print(token)

['Iam', 'going', 'college', 'today']


In [ ]:
import nltk
nltk.download('punkt_tab', quiet=True)
sentence = "I donot love spam email, do you"
basics = sentence.split()
print('BASIC SPLIT:' ,basics)
from nltk.tokenize import word_tokenize
smart = word_tokenize(sentence.lower())
print('NLTK TOKENIZE:', smart)

BASIC SPLIT: ['I', 'donot', 'love', 'spam', 'email,', 'do', 'you']
NLTK TOKENIZE: ['i', 'donot', 'love', 'spam', 'email', ',', 'do', 'you']


In [ ]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
nltk.download('wordnet', quiet=True)
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
words =['running','studies','better','caring','happily']
for word in words:
   stem = stemmer.stem(word)
   lemma = lemmatizer.lemmatize(word, pos='v')
   print(f'{word:12} | stem: {stem:10} | lemma: {lemma}')

running      | stem: run        | lemma: run
studies      | stem: studi      | lemma: study
better       | stem: better     | lemma: better
caring       | stem: care       | lemma: care
happily      | stem: happili    | lemma: happily


In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
nltk.download(['stopwords','wordnet','punkt'], quiet=True)
stop_word = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
def preprocess(text):
  text = text.lower()
  text = re.sub(r'[^a-z]', ' ', text)
  tokens = text.split()
  filtered_tokens = []
  for w in tokens:
    if w not in stop_word:
      filtered_tokens.append(w)
  tokens = filtered_tokens
  lemmatized_tokens = []
  for w in tokens:
    lemmatized_tokens.append(
    lemmatizer.lemmatize(w)
    )
  token = lemmatized_tokens
  return ' '.join(tokens)

print(preprocess('I am running to the store to buy books'))


running store buy books


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
emails = [
    'cricket match cricket match cricket',
    'free win money free win money win',
    'cricket match free win money cricket',

]
cv = CountVectorizer()
x = cv.fit_transform(emails).toarray()
print('Vocabulary:', cv.get_feature_names_out())
print('Bow matrix:')
print(x)

Vocabulary: ['cricket' 'free' 'match' 'money' 'win']
Bow matrix:
[[3 0 2 0 0]
 [0 2 0 2 3]
 [2 1 1 1 1]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
emails = [
    'cricket match cricket match cricket',
    'free win money free win money win',
    'cricket match free win money cricket',

]
tfidf = TfidfVectorizer(sublinear_tf=True, max_df=0.95, min_df=1)
x_tfidf = tfidf.fit_transform(emails).toarray()
print('Feature names:', tfidf.get_feature_names_out())
print('TFIDF matrix(rounded):')
import numpy as np
print(np.round(x_tfidf, 3))

Feature names: ['cricket' 'free' 'match' 'money' 'win']
TFIDF matrix(rounded):
[[0.778 0.    0.628 0.    0.   ]
 [0.    0.532 0.    0.532 0.659]
 [0.646 0.382 0.382 0.382 0.382]]


LAB

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/SMSSpamCollection', sep='\t',
header=None, names=['label', 'message'])

print(df.head())
print('\nShape:', df.shape)
print('\nClass balance:')
print(df['label'].value_counts())
print(f'Spam rate: {747/5574*100:.1f}%')

print('\nSpam example:')
print(df[df['label']=='spam']['message'].iloc[0])

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

Shape: (5572, 2)

Class balance:
label
ham     4825
spam     747
Name: count, dtype: int64
Spam rate: 13.4%

Spam example:
Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's


In [ ]:
import re, nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
nltk.download(['stopwords','wordnet'], quiet=True)
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
def preprocess(text):
  text = text.lower()
  text = re.sub(r'[^a-z ]', '', text)
  tokens = [w for w in text.split() if w not in stop_words]
  tokens = [lemmatizer.lemmatize(w) for w in tokens]
  return ' '.join(tokens)

df['clean'] = df['message'].apply(preprocess)

df['target'] = (df['label'] == 'spam').astype(int)

tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2),
sublinear_tf=True)
X = tfidf.fit_transform(df['clean'])
y = df['target'].values

X_tr, X_te, y_tr, y_te = train_test_split(
X, y, test_size=0.2, random_state=42, stratify=y
)
print(f'Train: {X_tr.shape}, Test: {X_te.shape}')

Train: (4457, 5000), Test: (1115, 5000)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (classification_report,
confusion_matrix, accuracy_score)
import seaborn as sns
import matplotlib.pyplot as plt

clf = LogisticRegression(C=1.0, max_iter=1000, random_state=42)
clf.fit(X_tr, y_tr)
y_pred = clf.predict(X_te)
print('Accuracy:', accuracy_score(y_te, y_pred))

print(classification_report(y_te, y_pred,
target_names=['Ham (genuine)', 'Spam']))

cm = confusion_matrix(y_te, y_pred)
print('Confusion matrix:')
print(cm)


Accuracy: 0.9659192825112107
               precision    recall  f1-score   support

Ham (genuine)       0.96      1.00      0.98       966
         Spam       1.00      0.74      0.85       149

     accuracy                           0.97      1115
    macro avg       0.98      0.87      0.92      1115
 weighted avg       0.97      0.97      0.96      1115

Confusion matrix:
[[966   0]
 [ 38 111]]


In [ ]:
def predict_spam(message):
  '''Predict if a new message is spam or ham.'''
  cleaned = preprocess(message)
  vector = tfidf.transform([cleaned])
  pred = clf.predict(vector)[0]
  prob = clf.predict_proba(vector)[0]
  label = 'SPAM' if pred==1 else 'HAM'
  conf = prob[pred]
  return f'{label} (confidence: {conf:.1%})'

messages = [
'Congratulations! You won a free iPhone. Click here to claim now!',
'Hey, are we still meeting at 6pm for dinner?',
'URGENT: Your bank account has been suspended. Verify now!',
'Can you pick up milk on the way home?',
]
for msg in messages:
  print(f'{predict_spam(msg):30} | {msg[:55]}...')


SPAM (confidence: 72.2%)       | Congratulations! You won a free iPhone. Click here to c...
HAM (confidence: 96.9%)        | Hey, are we still meeting at 6pm for dinner?...
HAM (confidence: 73.4%)        | URGENT: Your bank account has been suspended. Verify no...
HAM (confidence: 97.1%)        | Can you pick up milk on the way home?...


TASK

In [1]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download(['stopwords','wordnet'], quiet=True)
text = "Hello My name is sireesha. I am learning NLP, and it's AMAZING!  Running, runs, ran..."

text = text.lower()
text = re.sub(r'[^a-zA-Z\s]', '', text)

words = text.split()

print(words)

['hello', 'my', 'name', 'is', 'sireesha', 'i', 'am', 'learning', 'nlp', 'and', 'its', 'amazing', 'running', 'runs', 'ran']


In [2]:
stop_words = set(stopwords.words('english'))
words = [w for w in words if w not in stop_words]
print(words)

['hello', 'name', 'sireesha', 'learning', 'nlp', 'amazing', 'running', 'runs', 'ran']


In [3]:
lemmatizer = WordNetLemmatizer()
words = [lemmatizer.lemmatize(w) for w in words]
print(words)

['hello', 'name', 'sireesha', 'learning', 'nlp', 'amazing', 'running', 'run', 'ran']


In [ ]:
import pandas as pd

data = {
    "Sentence": [
        "I saw the man with the telescope.",
        "Oh wonderful, my internet stopped during the interview.",
        "He kicked the bucket yesterday.",
        "BRB, I need to answer a call.",
        "Chat is my favorite animal."
    ],

    "NLP Challenge": [
        "Ambiguity",
        "Sarcasm",
        "Context",
        "Abbreviation/Slang",
        "Multiple Language Issue"
    ],

    "Reason": [
        "Not clear who has the telescope.",
        "Wonderful is used sarcastically.",
        "Means died, not literal kicking.",
        "BRB means Be Right Back.",
        "Chat has different meanings in different languages."
    ]
}

df = pd.DataFrame(data)
print(df)

                                            Sentence            NLP Challenge  \
0                  I saw the man with the telescope.                Ambiguity   
1  Oh wonderful, my internet stopped during the i...                  Sarcasm   
2                    He kicked the bucket yesterday.                  Context   
3                      BRB, I need to answer a call.       Abbreviation/Slang   
4                        Chat is my favorite animal.  Multiple Language Issue   

                                              Reason  
0                   Not clear who has the telescope.  
1                   Wonderful is used sarcastically.  
2                   Means died, not literal kicking.  
3                           BRB means Be Right Back.  
4  Chat has different meanings in different langu...  


In [ ]:
import pandas as pd
docs = [
    "I love cricket",
    "I love football",
    "Cricket is my favorite sport"
]
stopwords = ['i', 'is', 'my']
processed_docs = []
for doc in docs:
    words = doc.lower().split()
    words = [word for word in words if word not in stopwords]
    processed_docs.append(words)
print("Preprocessed Documents:")
print(processed_docs)
vocab = []
for doc in processed_docs:
    for word in doc:
        if word not in vocab:
            vocab.append(word)
print("\nVocabulary:")
print(vocab)
bow = []
for doc in processed_docs:
    row = []
    for word in vocab:
        row.append(doc.count(word))
    bow.append(row)

bow_df = pd.DataFrame(
    bow,
    columns=vocab,
    index=['Doc1', 'Doc2', 'Doc3']
)

print("\nBag of Words Table:")
print(bow_df)

Preprocessed Documents:
[['love', 'cricket'], ['love', 'football'], ['cricket', 'favorite', 'sport']]

Vocabulary:
['love', 'cricket', 'football', 'favorite', 'sport']

Bag of Words Table:
      love  cricket  football  favorite  sport
Doc1     1        1         0         0      0
Doc2     1        0         1         0      0
Doc3     0        1         0         1      1
